apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PORT: "5000"
  MONGO_URI: "mongodb+srv://aliamjad7pkk:Etpgqqbrpt6KYn6j@cluster0.bft0d.mongodb.net/mern-project?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "ac77c31435f911f442fb696e6eb4a7b8156da34e1ccc1690675fcfe1ab71f7ec"
  EMAIL_USER: "aliamjad7pkk@gmail.com"
  EMAIL_PASS: "tjnoylryfagwgpaf"
  EMAIL_FROM: "ALITECH <aliamjad7pkk@gmail.com>"
